// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AIcon: typeof import('@arco-design/web-vue')['Icon']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    DataBox: typeof import('./src/components/DataBox.vue')['default']
    DropDownItem: typeof import('./src/components/DropDownItem.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
